// Generated by CoffeeScript 1.7.1
(function() {
  window.Giraf.Footage = (function() {
    function Footage(aaa) {
      this.aaa = aaa;
      console.log("footage const");
    }

    Footage.prototype.hoge = function() {
      return console.log("hoge: " + this.aaa);
    };

    return Footage;

  })();

}).call(this);
